[package]
name = "rudis-server"
version = "0.0.1"
authors = ["Jmys"]
edition = "2021"

[dependencies] 
anyhow = "1.0.59"                                  
bytes = "1.3.0"     
env_logger = "0.8"                                
thiserror = "1.0.32"                               
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
indicatif = "0.15.0"
regex = "1"
redis = "0.21.4"
log = "0.4"