[package]
name = "rudis-server"
version = "0.0.5"
authors = ["Jmys"]
edition = "2021"

[dependencies]                                 
bytes = "1.3.0"
anyhow = "1.0.59"       
env_logger = "0.8"                                
thiserror = "1.0.32"                               
serde_json = "1.0"
ahash = "0.8.11"
tokio = { version = "1.38.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
indicatif = "0.15.0"
regex = "1"
redis = "0.21.4"
log = "0.4"
clap = { version = "4.5.13", features = ["derive"] }
parking_lot = "0.12.3"
